import { Injectable } from '@nestjs/common';

import { Order } from './order.model';

@Injectable()
export class OrderService {
  getOrdersByCustomerId(customerId: number) {
    const orders = [
      {
        id: 1,
        storeId: 1,
        locationId: 1,
        number: 302,
        amount: 17000,
        discountAmount: 1000,
        customerId,
        storeCustomerId: 1,
        state: 'created',
        tax: 1700,
        quantity: 2,
        diningOption: 'takeout',
        diningState: 'delivered',
        phone: '01054030883',
        deviceId: 'uuid433-12345678-12323131',
        createdAt: new Date(),
        updatedAt: new Date(),
        paidAt: new Date(),
        pointSaved: 2,
        receiptNumber: '78994561235687',
        items: [
          {
            id: 1,
            orderId: 1,
            type: 'sku',
            productId: 1,
            skuId: 1,
            name: '아이스 아메리카노',
            amount: 7000,
            price: 7000,
            quantity: 1,
            tax: 700,
            diningOption: 'takeout',
            discountMethod: 'amount',
            discountValue: 1000,
            point: 1,
            createdAt: new Date(),
          },
          {
            id: 2,
            orderId: 1,
            type: 'sku',
            productId: 1,
            skuId: 2,
            name: '아이스 아메리카노',
            amount: 10000,
            price: 10000,
            quantity: 1,
            tax: 1000,
            diningOption: 'takeout',
            discountMethod: 'amount',
            point: 1,
            createdAt: new Date(),
          },
        ],
        charges: [
          {
            id: 1,
            orderId: 1,
            method: 'card',
            amount: 17000,
            tax: 1700,
            request: '빨리 주세요.',
            ident: '25030483939101290',
            approver: 'kb 국민',
            approvalDate: new Date(),
            approvalNumber: '13213145153214',
          },
        ],
      },
      {
        id: 2,
        storeId: 1,
        locationId: 1,
        number: 303,
        amount: 17000,
        discountAmount: 1000,
        customerId,
        storeCustomerId: 1,
        state: 'paid',
        tax: 1700,
        quantity: 2,
        diningOption: 'takeout',
        diningState: 'delivered',
        phone: '01054030883',
        deviceId: 'uuid433-12345678-12323131',
        createdAt: new Date(),
        updatedAt: new Date(),
        paidAt: new Date(),
        pointSaved: 2,
        receiptNumber: '78994561235687',
        items: [
          {
            id: 1,
            orderId: 2,
            type: 'sku',
            productId: 1,
            skuId: 1,
            name: '아이스 아메리카노',
            amount: 7000,
            price: 7000,
            quantity: 1,
            tax: 700,
            diningOption: 'takeout',
            discountMethod: 'amount',
            discountValue: 1000,
            point: 1,
            createdAt: new Date(),
          },
          {
            id: 2,
            orderId: 2,
            type: 'sku',
            productId: 1,
            skuId: 2,
            name: '아이스 아메리카노',
            amount: 10000,
            price: 10000,
            quantity: 1,
            tax: 1000,
            diningOption: 'takeout',
            discountMethod: 'amount',
            point: 1,
            createdAt: new Date(),
          },
        ],
        charges: [
          {
            id: 1,
            orderId: 2,
            method: 'card',
            amount: 17000,
            tax: 1700,
            request: '빨리 주세요.',
            ident: '25030483939101290',
            approver: 'kb 국민',
            approvalDate: new Date(),
            approvalNumber: '13213145153214',
          },
        ],
      },
      {
        id: 3,
        storeId: 1,
        locationId: 1,
        number: 304,
        amount: 17000,
        discountAmount: 1000,
        customerId,
        storeCustomerId: 1,
        state: 'paid',
        tax: 1700,
        quantity: 2,
        diningOption: 'takeout',
        diningState: 'delivered',
        phone: '01054030883',
        deviceId: 'uuid433-12345678-12323131',
        createdAt: new Date(),
        updatedAt: new Date(),
        paidAt: new Date(),
        pointSaved: 2,
        receiptNumber: '78994561235687',
        items: [
          {
            id: 1,
            orderId: 3,
            type: 'sku',
            productId: 1,
            skuId: 1,
            name: '아이스 아메리카노',
            amount: 7000,
            price: 7000,
            quantity: 1,
            tax: 700,
            diningOption: 'takeout',
            discountMethod: 'amount',
            discountValue: 1000,
            point: 1,
            createdAt: new Date(),
          },
          {
            id: 2,
            orderId: 3,
            type: 'sku',
            productId: 1,
            skuId: 2,
            name: '아이스 아메리카노',
            amount: 10000,
            price: 10000,
            quantity: 1,
            tax: 1000,
            diningOption: 'takeout',
            discountMethod: 'amount',
            point: 1,
            createdAt: new Date(),
          },
        ],
        charges: [
          {
            id: 1,
            orderId: 3,
            method: 'card',
            amount: 17000,
            tax: 1700,
            request: '빨리 주세요.',
            ident: '25030483939101290',
            approver: 'kb 국민',
            approvalDate: new Date(),
            approvalNumber: '13213145153214',
          },
        ],
      },
    ] as Order[];
    return orders;
  }

  getPaidOrdersByCustomerId(customerId: number) {
    const orders = this.getOrdersByCustomerId(customerId);

    return orders.filter((order) => order.state === 'paid');
  }

  getRecentOrdersByCustomerId(customerId: number) {
    const orders = this.getOrdersByCustomerId(customerId);
    return orders.slice(0, 5);
  }

  getOrderById(id: number) {
    const order = {
      id,
      storeId: 1,
      locationId: 1,
      number: 304,
      amount: 17000,
      discountAmount: 1000,
      customerId: 1,
      storeCustomerId: 1,
      state: 'paid',
      tax: 1700,
      quantity: 2,
      diningOption: 'takeout',
      diningState: 'delivered',
      phone: '01054030883',
      deviceId: 'uuid433-12345678-12323131',
      createdAt: new Date(),
      updatedAt: new Date(),
      paidAt: new Date(),
      pointSaved: 2,
      receiptNumber: '78994561235687',
      items: [
        {
          id: 1,
          orderId: 3,
          type: 'sku',
          productId: 1,
          skuId: 1,
          name: '아이스 아메리카노',
          amount: 7000,
          price: 7000,
          quantity: 1,
          tax: 700,
          diningOption: 'takeout',
          discountMethod: 'amount',
          discountValue: 1000,
          point: 1,
          createdAt: new Date(),
        },
        {
          id: 2,
          orderId: 3,
          type: 'sku',
          productId: 1,
          skuId: 2,
          name: '아이스 아메리카노',
          amount: 10000,
          price: 10000,
          quantity: 1,
          tax: 1000,
          diningOption: 'takeout',
          discountMethod: 'amount',
          point: 1,
          createdAt: new Date(),
        },
      ],
      charges: [
        {
          id: 1,
          orderId: 3,
          method: 'card',
          amount: 17000,
          tax: 1700,
          request: '빨리 주세요.',
          ident: '25030483939101290',
          approver: 'kb 국민',
          approvalDate: new Date(),
          approvalNumber: '13213145153214',
        },
      ],
    } as Order;
    return order;
  }
}
